### PR TITLE
chef-client 13 provider fix

### PR DESCRIPTION
**Pull request by Stromweld**

### CODE REVIEW

**Comment by Stromweld** [comment]
This should fix issue #6. I ran into the same issue with my internal supermarket server due to supermarket-omnibus-cookbook depends on this cookbook. I found this link pointing to the issue with chef-client 13. https://docs.chef.io/deprecations_chef_platform_methods.html. 

This officially breaks compatibility with chef-client 11 but should be backwards compatible with chef-client 12.

 I tested this on my CentOS 6.8 internal supermarket server and this worked to fix the issue with chef-client 13.

**Comment by irvingpop** [comment]
Thank you for your contribution @Stromweld !!

**Comment by irvingpop** [comment]
Just pushed 2.0.0 to supermarket  https://supermarket.chef.io/cookbooks/fancy_execute

**Comment by Stromweld** [comment]
thanks for the merge and for getting it into the supermarket so quick.

**Pull request merged**
