### PR TITLE
Begin the deprecation process

### PR DESCRIPTION
**Pull request by irvingpop**
Hopefully the readme says it all, but I'm using this PR to gather feedback until June 1st, 2017 when I'll officially deprecate

### CODE REVIEW

**Comment by lamont-granquist** [comment]
delete the entire repo with a commit that changes the README to say "this cookbook has been deprecated"

anyone who really needs the sources can use git history.

**Comment by lamont-granquist** [comment]
e.g.:  https://github.com/chef-boneyard/knife-terremark

**Comment by irvingpop** [comment]
At first glance that seems strong, but also feels like something future-me would thank you for :D

**Comment by lamont-granquist** [comment]
people will manage to miss the banner you put here -- google will also happily SEO on any other terms that come up -- github will index on the code that is in master.

it feels like you're "being nice" by keeping the code and the README around, but really it just perpetuates more damage to the world.  once something is deprecated the best thing you can do for newbies searching around in the dark is to largely obliterate the old information.  the number of users who really need that old information is very low, while the number of clueless newbies who might stumble across it and miss the deprecation warning is much larger.

**Comment by irvingpop** [comment]
thanks for the push @lamont-granquist - just pushed a commit for maximum deprecation :)

**Comment by lamont-granquist** [comment]
👍

**Pull request merged**
